<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Controllers;

use GetSatisfactionAPILib\APIException;
use GetSatisfactionAPILib\APIHelper;
use GetSatisfactionAPILib\Configuration;
use GetSatisfactionAPILib\Models;
use GetSatisfactionAPILib\Exceptions;
use GetSatisfactionAPILib\Http\HttpRequest;
use GetSatisfactionAPILib\Http\HttpResponse;
use GetSatisfactionAPILib\Http\HttpMethod;
use GetSatisfactionAPILib\Http\HttpContext;
use Unirest\Request;

/**
 * @todo Add a general description for this controller.
 */
class UserController extends BaseController {

    /**
     * @var UserController The reference to *Singleton* instance of this class
     */
    private static $instance;

    /**
     * Returns the *Singleton* instance of this class.
     * @return UserController The *Singleton* instance.
     */
    public static function getInstance()
    {
        if (null === static::$instance) {
            static::$instance = new static();
        }

        return static::$instance;
    }

    /**
     * Getting the authenticated user’s details
     * @param  bool        $includeArchived       Required parameter: Filter by Archived Topics
     * @param  integer     $activeSince           Optional parameter: Filter by the time of the last activity in the community. Time is set in seconds since epoch.
     * @param  string      $company               Optional parameter: Filter by company ID
     * @param  integer     $page                  Optional parameter: Page number
     * @param  string      $q                     Optional parameter: Search for a particular string
     * @param  string      $query                 Optional parameter: Search for a particular string
     * @param  string      $sort                  Optional parameter: Sort topics by value
     * @param  string      $status                Optional parameter: Filter by style
     * @param  string      $style                 Optional parameter: Filter by style
     * @param  string      $tag                   Optional parameter: Filter by tag
     * @param  string      $user                  Optional parameter: Filter by user ID
     * @param  string      $userDefinedCode       Optional parameter: Filter by Private Tags
     * @return mixed response from the API call
     * @throws APIException Thrown if API call fails
     */
    public function getTopicsJson (
        $includeArchived,
        $activeSince = 0,
        $company = NULL,
        $page = 1,
        $q = NULL,
        $query = NULL,
        $sort = NULL,
        $status = NULL,
        $style = NULL,
        $tag = NULL,
        $user = NULL,
        $userDefinedCode = NULL)
    {
        //the base uri for api requests
        $_queryBuilder = Configuration::$BASEURI;

        //prepare query string for API call
        $_queryBuilder = $_queryBuilder.'/topics.markdown';

        //process optional query parameters
        APIHelper::appendUrlWithQueryParameters($_queryBuilder, array (
            'include_archived'  => var_export($includeArchived, true),
            'active_since'      => (null != $activeSince) ? $activeSince : 0,
            'company'           => $company,
            'page'              => (null != $page) ? $page : 1,
            'q'                 => $q,
            'query'             => $query,
            'sort'              => $sort,
            'status'            => $status,
            'style'             => $style,
            'tag'               => $tag,
            'user'              => $user,
            'user_defined_code' => $userDefinedCode,
        ));

        //validate and preprocess url
        $_queryUrl = APIHelper::cleanUrl($_queryBuilder);

        //prepare headers
        $_headers = array (
            'user-agent'      => 'APIMATIC 2.0',
            'Accept'          => 'application/json'
        );

        //call on-before Http callback
        $_httpRequest = new HttpRequest(HttpMethod::GET, $_headers, $_queryUrl);
        if($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);
        }

        //and invoke the API call request to fetch the response
        $response = Request::get($_queryUrl, $_headers);

        $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
        $_httpContext = new HttpContext($_httpRequest, $_httpResponse);

        //call on-after Http callback
        if($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);
        }

        //handle errors defined at the API level
        $this->validateResponse($_httpResponse,$_httpContext);

        $mapper = $this->getJsonMapper();

        return $mapper->map($response->body, new Models\TopicsJsonResponse());
    }


}