<?php 
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CompaniesTopicsJsonByCompanyIdResponse implements JsonSerializable {
    /**
     * a list of topic objects within a data envelope
     * @var Datum[] $data public property
     */
    public $data;

    /**
     * number of results
     * @var integer $total public property
     */
    public $total;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $data    Initialization value for the property $this->data 
     * @param   integer           $total   Initialization value for the property $this->total
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->data  = func_get_arg(0);
            $this->total = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['data']  = $this->data;
        $json['total'] = $this->total;

        return $json;
    }
}