<?php 
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Emotitag implements JsonSerializable {
    /**
     * The emoticon face. Values are “happy”, “silly”, “indifferent”, and “sad”
     * @var string $face public property
     */
    public $face;

    /**
     * The text associated with the emoticon face.
     * @var string $feeling public property
     */
    public $feeling;

    /**
     * The intensity of the emoticon on a scale of 0 to 4. 0 – hides the emoticon, 1 – shows the emoticon, 2 – shows the emoticon with one exclamation mark, 3 – shows the emoticon with two exclamation marks, 4 – shows the emoticon with two exclamation marks
     * @var int $intensity public property
     */
    public $intensity;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $face        Initialization value for the property $this->face     
     * @param   string            $feeling     Initialization value for the property $this->feeling  
     * @param   int               $intensity   Initialization value for the property $this->intensity
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->face      = func_get_arg(0);
            $this->feeling   = func_get_arg(1);
            $this->intensity = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['face']      = $this->face;
        $json['feeling']   = $this->feeling;
        $json['intensity'] = $this->intensity;

        return $json;
    }
}