<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class FaceEnum {
    /**
     * TODO: Write general description for this element
     */
    const HAPPY = "happy";

    /**
     * TODO: Write general description for this element
     */
    const INDIFFERENT = "indifferent";

    /**
     * TODO: Write general description for this element
     */
    const SAD = "sad";

    /**
     * TODO: Write general description for this element
     */
    const SILLY = "silly";

}