<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class IntensityEnum {
    /**
     * TODO: Write general description for this element
     */
    const VALUE_0 = 0;

    /**
     * TODO: Write general description for this element
     */
    const VALUE_1 = 1;

    /**
     * TODO: Write general description for this element
     */
    const VALUE_2 = 2;

    /**
     * TODO: Write general description for this element
     */
    const VALUE_3 = 3;

    /**
     * TODO: Write general description for this element
     */
    const VALUE_4 = 4;

}