<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class MostRecentActivityEnum {
    /**
     * TODO: Write general description for this element
     */
    const COMMENT = "comment";

    /**
     * TODO: Write general description for this element
     */
    const CREATE = "create";

    /**
     * TODO: Write general description for this element
     */
    const FOLLOW = "follow";

}