<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class SortEnum {
    /**
     * TODO: Write general description for this element
     */
    const MOST_ME_TOOS = "most_me_toos";

    /**
     * TODO: Write general description for this element
     */
    const MOST_REPLIES = "most_replies";

    /**
     * TODO: Write general description for this element
     */
    const RECENTLY_ACTIVE = "recently_active";

    /**
     * TODO: Write general description for this element
     */
    const RECENTLY_CREATED = "recently_created";

    /**
     * TODO: Write general description for this element
     */
    const UNANSWERED = "unanswered";

}