<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class StatusEnum {
    /**
     * TODO: Write general description for this element
     */
    const ACTIVE = "active";

    /**
     * TODO: Write general description for this element
     */
    const COMPLETE = "complete";

    /**
     * TODO: Write general description for this element
     */
    const NONE = "none";

    /**
     * TODO: Write general description for this element
     */
    const PENDING = "pending";

    /**
     * TODO: Write general description for this element
     */
    const REJECTED = "rejected";

}