<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class StyleEnum {
    /**
     * TODO: Write general description for this element
     */
    const IDEA = "idea";

    /**
     * TODO: Write general description for this element
     */
    const PRAISE = "praise";

    /**
     * TODO: Write general description for this element
     */
    const PROBLEM = "problem";

    /**
     * TODO: Write general description for this element
     */
    const QUESTION = "question";

    /**
     * TODO: Write general description for this element
     */
    const UPDATE = "update";

}