<?php
/*
 * GetSatisfactionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GetSatisfactionAPILib;

use GetSatisfactionAPILib\Controllers;

/**
 * GetSatisfactionAPILib client class
 */
class GetSatisfactionAPIClient
{

    /**
     * Singleton access to Topic controller
     * @return Controllers\TopicController The *Singleton* instance
     */
    public function getTopic()
    {
        return Controllers\TopicController::getInstance();
    }

    /**
     * Singleton access to User controller
     * @return Controllers\UserController The *Singleton* instance
     */
    public function getUser()
    {
        return Controllers\UserController::getInstance();
    }
}